# -*- coding: utf-8 -*-
"""day_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kwqvDti8jJq4t2n35MM1KBlyJ_4fP-DY
"""

# Declare variables of different data types
integer_var = 10
float_var = 3.14
string_var = "Hello, Jupyter!"
boolean_var = True

# Print each variable and its type
print("Integer Variable: ", integer_var, " Type: ", type(integer_var))
print("Float Variable: ", float_var, " Type: ", type(float_var))
print("String Variable: ", string_var, " Type: ", type(string_var))
print("Boolean Variable: ", boolean_var, " Type: ", type(boolean_var))